name: Android CI
'on':
  pull_request:
    branches:
      - main
  push:
    branch: dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: zulu
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Grant rights
        run: chmod +x build.gradle

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{
            hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{
            hashFiles('**/buildSrc/**/*.kt') }}

#      - name: Execute Gradle build
#        run: ./gradlew build

#      - name: Run Ktlint
#        run: ./gradlew ktlintStagingDebugCheck

#      - name: Run Unit Tests
#        run: ./gradlew testDebugUnitTest

#      - name: Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 23
#          target: default
#          arch: x86_64
#          profile: Nexus 6
#          script: ./gradlew connectedCheck --stacktrace

#      - name: Bump version code
#        uses: chkfung/android-version-actions@v1.1
#        with:
#          gradlePath: app/build.gradle
#          versionCode: ${{github.run_number}}

      - name: Build Release AAB with Gradle
        run: ./gradlew clean bundleRelease

      - name: Sign Release AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          releaseName: Version 1.0.4
          serviceAccountJson: service_account.json
          packageName: com.latticeonfhir.android
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: inProgress
          userFraction: 1.00
          inAppUpdatePriority: 5
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/build/intermediates/merged_native_libs/release/out/lib
