name: Patch Non Fhir Build

on:
  pull_request:
    branches:
      - patch-nonclinical-nonfhirsdk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle Version 8.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1

      - name: Grant rights
        run: chmod +x build.gradle

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{
            hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{
            hashFiles('**/buildSrc/**/*.kt') }}

      - name: Execute Gradle build
        run: ./gradlew build