name: Build

on:
  push:
    branches:
      - development-nonfhirsdk

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.2
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
          SONAR_HOST_URL: '${{ secrets.SONAR_HOST_URL }}'
        with:
          args: >
            -Dsonar.projectKey=<PROJECT_KEY>
            -Dsonar.projectName=<PROJECT_NAME>
            -Dsonar.host.url=<SONAR_HOST_URL>
            -Dsonar.scm.provider=git 
            -Dsonar.projectVersion=${{github.run_id}}