name: Build

on:
  pull_request:
    types:
      - closed
    branches:
      - development-nonfhirsdk

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.2
        env:
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
          SONAR_HOST_URL: '${{ secrets.SONAR_HOST_URL }}'
        with:
          args: >
            -Dsonar.projectKey=LatticeInnovations_FHIR-Android_AZAvReGoi3XM6MLXDS_L
            -Dsonar.projectName=FHIR-Android
            -Dsonar.host.url=https://sonarcube.thelattice.in/
            -Dsonar.scm.provider=git 
            -Dsonar.projectVersion=${{github.run_id}}